In [1]:
import numpy as np

In [3]:
def neuron_output(x1,x2,w1,w2,b):
    z = w1 * x1 + w2 * x2 + b
    return z

x1 = 5
x2 = 2

w1 = 0.8
w2 = 1.2
b = -1.0

z = neuron_output(x1, x2, w1, w2, b)
print("Linear combination (z): ",z)

Linear combination (z):  5.4


In [31]:
# Tiny 2-layer neural network forward pass (no training)
np.random.seed(42)

#Input: 1 Features
x1 = np.array([[2],
            [1]]) # shape(2,1)
x1

array([[2],
       [1]])

In [42]:
#Hidden layer:3 neurons
W1 = np.random.rand(3,2) # weight for hidden layer (3,2)
b1 = np.random.rand(3,1) # bias for hidden layer (3,1)

print(f'W:\n{W1}\nB:\n{b1}')

W:
[[0.29122914 0.61185289]
 [0.13949386 0.29214465]
 [0.36636184 0.45606998]]
B:
[[0.78517596]
 [0.19967378]
 [0.51423444]]


In [43]:
W2 = np.random.rand(1,3)
b2 = np.random.rand(1,1)

print(f'W2:\n{W2}\nB:\n{b2}')

W2:
[[0.59241457 0.04645041 0.60754485]]
B:
[[0.17052412]]


In [44]:
def relu(z):
    return np.maximum(0,z)

def sigmoid(z):
    return 1/ (1 + np.exp(-z))

In [45]:
# Forward pass
# Hidden layer

z1 = np.dot(W1,x1) + b1 # linear
a1 = relu(z1)           # activation
print(f'z1:\n{z1}\na1:\n{a1}')

z1:
[[1.97948714]
 [0.77080615]
 [1.70302811]]
a1:
[[1.97948714]
 [0.77080615]
 [1.70302811]]


In [46]:
z2 = np.dot(W2,a1) + b2 # linear
a2 = sigmoid(z2)           # activation
print(f'z2:\n{W2}na2:\n{b2}')

z2:
[[0.59241457 0.04645041 0.60754485]]na2:
[[0.17052412]]


In [47]:
print("Input x:\n", x1)
print("\nHidden layer activation (a1, after ReLU):\n", a1)
print("Output layer linear output (z2):\n", z2)
print("\nFinal output (a2, after sigmoid - can be seen as probability): \n", a2)

Input x:
 [[2]
 [1]]

Hidden layer activation (a1, after ReLU):
 [[1.97948714]
 [0.77080615]
 [1.70302811]]
Output layer linear output (z2):
 [[2.41367137]]

Final output (a2, after sigmoid - can be seen as probability): 
 [[0.91786389]]
