In [21]:
print("Hello Noor")

Hello Noor


In [22]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np


bring numpy library to the notebook/workbook . kernel

In [ ]:
#check version 
np.__version__

#' . notation , try to access the method of class

'2.3.5'

In [178]:
python_list = [1,2,3,"string",6.7]
numslist = [x for x in range(10)]
print(numslist)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [26]:
print(numslist*3)
print(type(numslist))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [27]:
arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [28]:
print(arr1*3)
print(type(arr1))

[ 3  6  9 12]
<class 'numpy.ndarray'>


In [29]:
arr1D=np.array([1, 2, 3])
print(arr1,"\n",arr1D.ndim)

[1 2 3 4] 
 1


In [30]:
arr2D = np.array([[1, 2, 3],
                 [1, 2, 3]])
print(arr2D,"\n",arr1D.ndim)

[[1 2 3]
 [1 2 3]] 
 1


In [31]:
arr3D = np.array([[[1, 2, 3],[1, 2, 3]],
                  [[1, 2, 3],[1, 2, 3]]])
print(arr3D,"\n",arr1D.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 
 1


In [32]:
x = np.array([])
type(x)

numpy.ndarray

In [33]:
# ndim works on obj and checks their dimention

print(f"dimension are: {arr1D.ndim}")

print(f"dimension are: {arr2D.ndim}")

print(f"dimension are: {arr3D.ndim}")


# using np. methof, for checking the dimesion of an arrat
# (rows,column)
print(f"dimension are: {np.shape(arr1D)}")

print(f"dimension are: {np.shape(arr2D)}")

print(f"dimension are: {np.shape(arr3D)}")

#ndim tells us abt dimension
#to change type
arr1D.dtype



dimension are: 1
dimension are: 2
dimension are: 3
dimension are: (3,)
dimension are: (2, 3)
dimension are: (2, 2, 3)


dtype('int64')

In [34]:
# to check shape and size, h0ow large , how many elements
shape1D = arr1D.ndim
shape1D

size1D = arr1D.size
size1D

size2D = arr2D.size
size2D

size3D = arr3D.size
size3D

12

In [35]:
type(arr1D)

numpy.ndarray

In [36]:
arr1D.shape


(3,)

In [37]:
arr1D + arr1D

array([2, 4, 6])

In [38]:
print(arr1)

[1 2 3 4]


In [39]:
#broadcasting

arr1D * 30

array([30, 60, 90])

In [40]:
arr1D + arr1D

array([2, 4, 6])

In [47]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2= np.array([10,20,30,40,50])
print(arr2)

print(arr1 + arr2)

print("result: ",arr1+arr2)

[1 2 3 4 5]
[10 20 30 40 50]
[11 22 33 44 55]
result:  [11 22 33 44 55]


In [50]:
a = 10
b= 3

print(a+b) #addition 13
print(a-b) # subtraction 7
print(a*b) #multiplication 30
print(a/b) #division 3.333
print(a//b) # floor division 3
print(a%b) #modulus 1
print(a**b) #exponention 1000

13
7
30
3.3333333333333335
3
1
1000


In [ ]:
prices = np.array([4000000,2000000,3000000])
print(f"the prices are: {prices/1000000} million") # scaling, using broaDCASTIONG OPERATION

the prices are: [4. 2. 3.] million


- slicing
- reshaping

In [ ]:
# only list comprehension we have used
nums = [x for x in range(0,100,2)]
print (nums)

nums.size

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [ ]:
# : acess all the objects
nums1=nums[0]
nums1=nums[:]



print(nums1)

[]


In [ ]:
nums1=nums[100:0:-1]

# convert list to array using np.array
arraynums = np.array(nums)
print(arraynums)

print(arraynums[::2])

#to print everything
print(arraynums[:])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [ ]:
line = np.linspace(0,1,10) # values are evenly spaced and stored in array BREAK 0 ->1 INTO 10 STEPS
line 

#EXERCISE RESULT SHOULD BE LIKE THIS
# 0 0.1 0.2 0.3 0.4

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.zeros((3,3))
np.ones((4,3))

#take in tuples of shape, and return arrays

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [167]:
# arrange
# easiest way to create an array quickly
range_of_numbers = np.arange(1,11)
range_of_numbers.reshape(5,2)
print(range_of_numbers)
#test

#exactly same as this
range_example = np.arange(1,11).reshape(5,2)
print(range_example)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
# random class in numpy
#numbers

np.random.seed(40) 

randomArray = np.random.rand(3,4)
randomArray

randomArray = np.random.randint(0,100,(3,3))
randomArray

array([[52, 30, 79],
       [14, 92, 58],
       [74, 22,  3]], dtype=int32)

In [ ]:
np.random.seed(40)

# randomArray = np.random.rand(3,4)
# randomArray


#randit to make it integer
randomArray = np.random.randint(0,100,(3,4)) # start,stop, (shape)
randomArray

array([[70, 91,  7, 37],
       [56, 50, 65, 12],
       [71, 19, 31, 74]], dtype=int32)

In [134]:
# change and reshape array
# 

In [ ]:
# untuk jadikan 1D
flatarray = randomArray.flatten()
flatarray

reshapearray = flatarray.reshape(6,2)
reshapearray

array([[70, 91],
       [ 7, 37],
       [56, 50],
       [65, 12],
       [71, 19],
       [31, 74]], dtype=int32)

In [137]:
#transform
reshapearray.T

array([[70,  7, 56, 65, 71, 31],
       [91, 37, 50, 12, 19, 74]], dtype=int32)

In [ ]:
# aggregation

data = np.array([85,94,22,68,94.54,98]) # marks

#sum
#mean
#max

print(data.sum())





461.54


In [150]:
# EXERCISE 
# create a list of 1 to 10
# use list comprehension
#give me the addition of numbers from 1 to 10

numbers = [x for x in range(1, 11)]
print(numbers)

total = sum(numbers)
total

#ANSWER#

array_noor = np.array([num for num in range(1,11)])
sum_of_array_noor = array_noor.sum() 
print(sum_of_array_noor)
array_noor.mean()
array_noor.max()
#list comprehension helps us create list quickly
#

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
55


np.int64(10)

Whole thinggg

but we can also go, column wise

or

row wise

In [154]:
#                      matrix using tuples
a_2d_matrix = np.ones((3,5))
a_2d_matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# column wise sum 
#check this first 
a_2d_matrix.sum(axis=0)
# then check this (row wise)
a_2d_matrix.sum(axis=1)

array([5., 5., 5.])

In [177]:
###splitting numpy arrays
dataset_array = np.arange(1,101).reshape(50,2)
print(dataset_array)


# x input ----> y output
# # 1 ----> 2

#rows are 50

train_dataset = dataset_array[:10] # to give 10 rows
train_dataset = dataset_array[:10]
train_dataset


[[  1   2]
 [  3   4]
 [  5   6]
 [  7   8]
 [  9  10]
 [ 11  12]
 [ 13  14]
 [ 15  16]
 [ 17  18]
 [ 19  20]
 [ 21  22]
 [ 23  24]
 [ 25  26]
 [ 27  28]
 [ 29  30]
 [ 31  32]
 [ 33  34]
 [ 35  36]
 [ 37  38]
 [ 39  40]
 [ 41  42]
 [ 43  44]
 [ 45  46]
 [ 47  48]
 [ 49  50]
 [ 51  52]
 [ 53  54]
 [ 55  56]
 [ 57  58]
 [ 59  60]
 [ 61  62]
 [ 63  64]
 [ 65  66]
 [ 67  68]
 [ 69  70]
 [ 71  72]
 [ 73  74]
 [ 75  76]
 [ 77  78]
 [ 79  80]
 [ 81  82]
 [ 83  84]
 [ 85  86]
 [ 87  88]
 [ 89  90]
 [ 91  92]
 [ 93  94]
 [ 95  96]
 [ 97  98]
 [ 99 100]]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

#create one class
#one attribute saves name
# one method welcome(name) return welcome name!!!

In [23]:
class greet:
    def __init__(self,name):
        self.name=name
    
    def __str__(self):    
        return f"Selamat pagi {self.name}"

In [24]:
me =greet('noor')
print(me)

Selamat pagi noor


In [ ]:
class SelamatDatang:
    name='noor'
    
    def welcome(name):
        return f"Selamat Datang: {name}!!!"