In [2]:
import numpy as np

print(np.__version__)

2.3.5


In [3]:
#create a list of numbers
my_list=[1,2,3,4]
my_list = my_list* 2
print(my_list)

#hasil list biasa dia just gandakn sahaja


[1, 2, 3, 4, 1, 2, 3, 4]


In [4]:
#1
array = np.array([1,2,3,4])
print(array)

#tahu class
print(type(array))

#multiply by 2
array = array * 2
print(array)

[1 2 3 4]
<class 'numpy.ndarray'>
[2 4 6 8]


In [5]:
#2
#zero dymensional array
array = np.array('A')

#to print number of dimesnion
print(array.ndim)

0


In [6]:
#1D array
array1=np.array(['A','B','C'])
print(array1.ndim)

1


In [7]:
array2=np.array([['A','B','C'],
                 ['D','E','F'],
                 ['G','H','I']])

print(array2.ndim)

2


In [10]:
array3=np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                 [['J','K','L'],['M','N','O'],['P','Q','R']],
                 [['S','T','U'],['V','W','X'],['Y','Z',' ']]])
#                                             BIL KENA SAMA

print(array3.ndim)

#to find out the shape attribute
print(array3.shape)
#jawapan (3,3,3) merukuk kpd layers,rows,column . layers is selapis like cake

3
(3, 3, 3)


In [ ]:
#multidimension indexing

print(array3[0,0,0])
print(array3[1,1,1]) # layer 1, row 1 column 1

A
N


In [16]:
word = array3[0,0,0] + array3[2,0,0]
print(word)

AS


In [19]:
array4 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,16]])

#array[start:end:step] to access array

print(array4[0])
print(array4[-1])

print(array4[0:3])


[1 2 3 4]
[13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
print(array4[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [24]:
#return the column 
print(array4[:,2])

[ 3  7 11 15]
