In [1]:
import numpy as np

print(np.__version__)

2.3.5


In [2]:
#create a list of numbers
my_list=[1,2,3,4]
my_list = my_list* 2
print(my_list)

#hasil list biasa dia just gandakn sahaja


[1, 2, 3, 4, 1, 2, 3, 4]


In [3]:
#1
array = np.array([1,2,3,4])
print(array)

#tahu class
print(type(array))

#multiply by 2
array = array * 2
print(array)

[1 2 3 4]
<class 'numpy.ndarray'>
[2 4 6 8]


In [4]:
#2
#zero dymensional array
array = np.array('A')

#to print number of dimesnion
print(array.ndim)

0


In [5]:
#1D array
array1=np.array(['A','B','C'])
print(array1.ndim)

1


In [17]:
array2=np.array([['A','B','C'],
                 ['D','E','F'],
                 ['G','H','I']])

print(array2.ndim)

2


In [7]:
array3=np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                 [['J','K','L'],['M','N','O'],['P','Q','R']],
                 [['S','T','U'],['V','W','X'],['Y','Z',' ']]])
#                                             BIL KENA SAMA

print(array3.ndim)

#to find out the shape attribute
print(array3.shape)
#jawapan (3,3,3) merukuk kpd layers,rows,column . layers is selapis like cake

3
(3, 3, 3)


In [8]:
#multidimension indexing

print(array3[0,0,0])
print(array3[1,1,1]) # layer 1, row 1 column 1

A
N


In [9]:
word = array3[0,0,0] + array3[2,0,0]
print(word)

AS


In [10]:
array4 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,16]])

#array[start:end:step] to access array

print(array4[0])
print(array4[-1])

print(array4[0:3])


[1 2 3 4]
[13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
print(array4[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [12]:
#return the column 
print(array4[:,2])

[ 3  7 11 15]


In [14]:
print(array4[:, ::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [15]:
print(array4[0:2, 0:2])

[[1 2]
 [5 6]]


In [16]:
print(array4[0:2, 2:])

[[3 4]
 [7 8]]


In [19]:
print(array4[2:, 0:2])

[[ 9 10]
 [13 14]]


In [20]:
print(array4[2: , 2:])

[[11 12]
 [15 16]]


In [ ]:
# scalar arithmetic  - only single value

array = np.array([1,2,3])

print(array +1)
print(array *3)

[2 3 4]
[3 6 9]


In [26]:
#vectorized math function

array = np.array([1.5,2.56,3.00])

print(np.sqrt(array))
print(np.round(array))
print(np.floor(array)) #round down
print(np.ceil(array)) #round up

[1.22474487 1.6        1.73205081]
[2. 3. 3.]
[1. 2. 3.]
[2. 3. 3.]


In [31]:
array1 =np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 * array2)

[5 7 9]
[ 4 10 18]


In [33]:
#comparison operators

scores = np.array([91,44,55,63,88, 100])

print(scores ==100)

[False False False False False  True]


In [ ]:
# broadcasting allows NumPy to perform operations on arrays
# with different shapes by virtually expanding dimensions
# so they match the larger array's shape.

# the dimensions have the same size
# OR
# One of the dimensions has a size of 1

In [ ]:
array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])

print(array1.shape) #salah satu mesti 1 for comparing column and row 
print(array2.shape)

(1, 4)
(4, 1)


In [ ]:
# Aggregate functions = summarize data and typically return a single value

array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])

print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.argmin(array)) # gives index of min value

55
5.5
2.8722813232690143
8.25
1


In [ ]:
print(np.sum(array, axis=0))
print(np.sum(array, axis=1))

[15 40]


In [ ]:
# filtering = refers to the process off selecting elements from an array that matches a fiven condition

ages = np.array([[21,17,19,20,16,30,18,65],
                [39, 22, 15, 99, 18, 19, 20, 21]])

teenagers = ages[ages < 18]
print(teenagers)

adults = ages[(ages >=18) & (ages < 65)]
print(adults)

adults = np.where(ages >=18, ages, 0) # selain dari over 18 , ganti nilai dgn 0
print(adults)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


In [68]:
rng = np.random.default_rng(seed=1) #seed untuk reproduce same result
print(rng.integers(low=1,high= 101,size=(3,2)))

[[48 52]
 [76 96]
 [ 4 15]]


In [ ]:
print(np.random.uniform()) # each value has equal chance to be selected

In [76]:
# shuffle
rng= np.random.default_rng()
array = np.array([1,2,3,4,5])
rng.shuffle(array)
print(array)

[2 1 4 5 3]


In [ ]:
fruits = np.array(["apple","orange","banana","coconut"])
fruit = rng.choice(fruits,size=2) #size untuk berapa buah kita nak
print(fruit)

coconut
