-data -

- iris: [sepal length]
- titanic: [pclass,sibsp]

Columns = vectors

In [2]:
vector1 = [30,4,10]
vector2 = [20,4,10]
vector3 = [30,4,10]
type(vector1)



list

In [3]:
matrix = [vector1,vector2]

In [4]:
list2 = [3,4,5,'idrees',4.5,[3,['a','b'],5]]
list2[5][1][0]

'a'

In [8]:
import numpy as np

arr = np.array(vector1)

type(arr)
arr.mean()
arr.max()

np.int64(30)

In [10]:
vector1 = [30,4,10]
vector2 = [20,4,10]
vector3 = [30,4,10]

matrix = [[30,4,10],
          [20,4,10],
          [30,4,10]
    
]
matrix[0][1]

4

In [11]:
matrix = [[30,4,10],
          [20,4,10],
          [30,4,10]
    
]

matrixarr = np.array(matrix)
type(matrixarr)

numpy.ndarray

In [13]:
matrixarr.ndim

2

In [ ]:
#2Dimensional is when we have rows and columns

In [15]:
matrixarr[1][1]

np.int64(4)

In [ ]:
matrixarr[1:2][0] # 0 tu sebb before dah jadi new matrix so start dari 0 balik

array([20,  4, 10])

In [ ]:
matrixarr * 2 # scalar multiplication # broadcastinggggggggggg

# scalar pperations with arrays 

matrixarr * 2 

array([[60,  8, 20],
       [40,  8, 20],
       [60,  8, 20]])

In [ ]:
matrixarr.shape # rows x columns

(3, 3)

In [26]:
matrixarr + 10

array([[40, 14, 20],
       [30, 14, 20],
       [40, 14, 20]])

In [ ]:
a = np.array([1,3,5])
b = np.array([10,10,10]) # nak broadcast shape mesti sama

a+b

array([11, 13, 15])

In [36]:
a = np.array([[1,3,5,6],
             [2,8,7,9]]
             )
b = np.array([10,10,10,10]) # shape at least one mesti sama

print (a + b)
print (a - b)
print (a * b)

[[11 13 15 16]
 [12 18 17 19]]
[[-9 -7 -5 -4]
 [-8 -2 -3 -1]]
[[10 30 50 60]
 [20 80 70 90]]


In [32]:
a.shape


(2, 4)

In [33]:
b.shape

(4,)

In [37]:
a1 = np.array([[1,3,5,6],
             [2,8,7,9]]
             )
b2 = np.array([[10],
             [100]])

print (a1 + b2)
print (a1 - b2)
print (a1 * b2)

[[ 11  13  15  16]
 [102 108 107 109]]
[[ -9  -7  -5  -4]
 [-98 -92 -93 -91]]
[[ 10  30  50  60]
 [200 800 700 900]]


In [39]:
variance = np.array([454545,65645,745454,7676767])

n = np.array([145,445,656,768])

((variance)**0.5).round()


array([ 674.,  256.,  863., 2771.])

In [42]:
covariance = np.array([454545,656455])

n = np.array([145,445,656,768])

stdx , stdy = np.array([ 674.,  256.7])
stdx
stdy

r = covariance/(stdx*stdy)
r

array([2.62718781, 3.79419105])

In [45]:
x = np.array([[1,4,1],
              [2,5,2]]
              )

w = np.array([10,10,10])

matmultiply_xw = np.dot(x,w)
matmultiply_xw

array([60, 90])

In [46]:
w2 = np.array([[10,2,3],[10,2,3],[10,2,3]])
matmultiply_xw2 = np.dot(x,w2)
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])

In [ ]:
matmultiply_xw2 = x @ w2 # better way 
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])